// The human phrase for every action key logActivity() writes, shared by the live
// activity log and the v2 settings one. Pure data: no database import, so either
// side can read it.

export const ACTION_LABELS: Record<string, string> = {
  "auth.signed_in": "signed in",
  "audit.created": "created an audit",
  "audit.updated": "edited an audit",
  "audit.deleted": "deleted an audit",
  "news.created": "published a news post",
  "news.updated": "edited a news post",
  "news.deleted": "deleted a news post",
  "guide.created": "published a guide",
  "guide.updated": "edited a guide",
  "guide.deleted": "deleted a guide",
  "guide.game_added": "added a game",
  "specialty.added": "assigned a game specialty",
  "specialty.removed": "removed a game specialty",
  "specialty.game_added": "added a game",
  "specialty.game_renamed": "renamed a game",
  "specialty.game_deleted": "deleted a game",
  "board.task_created": "added a board card",
  "board.task_moved": "moved a board card",
  "board.task_deleted": "deleted a board card",
  "board.comment_added": "commented on a board card",
  "board.comment_deleted": "deleted a board comment",
  "board.member_assigned": "assigned a member to a card",
  "board.member_unassigned": "unassigned a member from a card",
  "note.created": "posted a note",
  "note.deleted": "deleted a note",
  "commission.submitted": "submitted a commission",
  "commission.reviewed": "reviewed a commission",
  "commission.deleted": "deleted a commission",
  "dispute.created": "logged a dispute",
  "dispute.deleted": "deleted a dispute",
  "dispute.category_created": "added a dispute category",
  "dispute.category_renamed": "renamed a dispute category",
  "dispute.category_deleted": "deleted a dispute category",
  "payment.eligible": "marked a member eligible for payment",
  "payment.ineligible": "marked a member ineligible for payment",
  "payment.payout_updated": "updated a member payout",
  "payment.saved": "saved payment changes",
  "payment.member_hidden": "hid a member from payments",
  "payment.member_shown": "restored a member to payments",
  "payment.period_added": "added a payment history period",
  "payment.period_updated": "edited a payment history period",
  "payment.period_duplicated": "duplicated a payment history period",
  "payment.period_deleted": "deleted a payment history period",
  "payment.tickets_updated": "edited a member's ticket count",
  "payment.tickets_reset": "reset a member's ticket count to live",
  "payment.base_updated": "edited a member's base compensation",
  "payment.role_assigned": "set a member's payment role",
  "payment.role_created": "added a payment role",
  "payment.role_renamed": "renamed a payment role",
  "payment.role_deleted": "deleted a payment role",
  "payment.role_paytype": "changed a role's pay type",
  "payment.role_bonus": "changed a role's recovered-revenue field",
  "comp.period_created": "started a pay period",
  "comp.period_updated": "edited a pay period",
  "comp.period_deleted": "deleted a pay period",
  "comp.tickets_synced": "synced ticket counts",
  "review.added": "logged a review",
  "review.deleted": "deleted a review",
  "review.assigned": "credited a review to a member",
  "review.bonus_updated": "updated the review bonus rule",
  "review.eligibility_set": "set a member's review bonus eligibility",
  "review.source_created": "added a review source",
  "review.source_renamed": "renamed a review source",
  "review.source_deleted": "deleted a review source",
  "report_period.deleted": "deleted a report period",
  "bot.token_set": "set the bot token",
  "bot.token_cleared": "cleared the bot token",
  "bot.presence_updated": "updated the bot presence",
  "bot.run_now": "ran the bot report now",
  "bot.announcement_updated": "updated the announcement settings",
  "bot.channel_added": "added a report channel",
  "bot.channel_deleted": "removed a report channel",
  "bot.channel_reset": "reset a report channel",
  "bot.reset_all": "reset all report channels",
  "bot.period_days": "changed the period length to",
  "invite.created": "invited a member",
  "invite.revoked": "revoked an invite",
  "member.role_changed": "changed a member's role",
  "member.removed": "removed a member",
};

/** The phrase for an action key, falling back to the raw key. */
export function describeAction(action: string): string {
  return ACTION_LABELS[action] ?? action;
}

/** The section an action belongs to, taken from the part before the dot. */
export function actionGroup(action: string): string {
  const dot = action.indexOf(".");
  return dot === -1 ? action : action.slice(0, dot);
}
